### ISSUE TITLE
System ("pasuse")

### ISSUE THREAD

**Issue by Reductions** [Scorpion333/fmi-up-2016#1]
Доста лош е да ги учи да лепят System ("pause") в кода.

**Comment by Scorpion333** [comment]
Чувал съм, че не е най-добрия вариант, но мен не ме научиха на друго.
Искам конзолата да остане отворена, за да видя резултата от програмата, но тя се затваря.
Така или иначе, не се фокусираме върху това, а върху останалата част от кода.

Все пак бих се радвал, ако ми кажеш какво мога да направя (на Visual Studio), за да избегна писането на паузата. :)

**Comment by Reductions** [comment]
Когато билдваш с VS можеш да сложиш брейк поинт на линията в мейна ти с с "return 0".
Независимо дали се фокусирате или не върху това, ако на домашното някой предаде код със system("pause") ще получи 0 точки тък като изхода от програмата няма да е това което търсим.

**Comment by Reductions** [comment]
[Това го намерих след 20 секунди търсене](http://stackoverflow.com/questions/4164077/c-on-windows-the-console-window-just-flashes-and-disappears-whats-going-on)

**Comment by Scorpion333** [comment]
TLDR - Съжалявам да го кажа, Слави, но предложенията ти непомагат.  Все пак ти благодаря, че ми каза това за домашните - ще инструктирам първокурсниците за това. Утре имам СДП и ще разбера някои неща директно от лектора си.

Слагането на брейкпойнт не помага (или може би не знам как да го направя, не изключвам възможността аз да съм много зле). Това е без да дебъгвам, но ми се струва, че дебъгърът не трябва да се включва при всяко пускане на програмата.
Търсил съм в Гугъл (и днес също), но най-доброто, на което съм попадал, е една настройка на проекта, която обаче трябва да се прави на всеки проект и всъщност май пак казва на системата да направи пауза.
От 20 секундното ти търсене разбрах, че трябва да пиша cin в края на програмата - едно работещо, но по мое мнение отчаяно и крайно решение.
Ще кажа на студентите си какво да не пишат в домашните, но не мисля да ги спирам да паузират системата по време на упражненията.
